/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CelebrationRouteImport } from './routes/celebration'
import { Route as MapRouteImport } from './routes/map'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as SortingRouteImport } from './routes/sorting'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrationRoute = CelebrationRouteImport.update({
  id: '/celebration',
  path: '/celebration',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const SortingRoute = SortingRouteImport.update({
  id: '/sorting',
  path: '/sorting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/celebration': typeof CelebrationRoute
  '/map': typeof MapRoute
  '/platform': typeof PlatformRoute
  '/sorting': typeof SortingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/celebration': typeof CelebrationRoute
  '/map': typeof MapRoute
  '/platform': typeof PlatformRoute
  '/sorting': typeof SortingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/celebration': typeof CelebrationRoute
  '/map': typeof MapRoute
  '/platform': typeof PlatformRoute
  '/sorting': typeof SortingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/celebration' | '/map' | '/platform' | '/sorting'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/celebration' | '/map' | '/platform' | '/sorting'
  id: '__root__' | '/' | '/celebration' | '/map' | '/platform' | '/sorting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CelebrationRoute: typeof CelebrationRoute
  MapRoute: typeof MapRoute
  PlatformRoute: typeof PlatformRoute
  SortingRoute: typeof SortingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebration': {
      id: '/celebration'
      path: '/celebration'
      fullPath: '/celebration'
      preLoaderRoute: typeof CelebrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorting': {
      id: '/sorting'
      path: '/sorting'
      fullPath: '/sorting'
      preLoaderRoute: typeof SortingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CelebrationRoute: CelebrationRoute,
  MapRoute: MapRoute,
  PlatformRoute: PlatformRoute,
  SortingRoute: SortingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
